{% set name = "bazel_buildozer" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/buildtools/archive/{{ version }}.tar.gz
  sha256: 05eff86c1d444dde18d55ac890f766bce5e4db56c180ee86b5aacd6704a5feb9
  folder: src/github.com/bazelbuild/buildtools

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} >=1.12

test:
  commands:
    - buildozer --version

about:
  home: https://github.com/bazelbuild/buildtools
  license: Apache-2.0
  license_family: APACHE
  license_file: src/github.com/bazelbuild/buildtools/LICENSE
  summary: Buildozer is a command line tool to rewrite multiple Bazel BUILD files using standard commands.
  doc_url: https://github.com/bazelbuild/buildtools/blob/{{ version }}/buildozer/README.md
  dev_url: https://github.com/bazelbuild/buildtools

extra:
  recipe-maintainers:
    - asford
    - rymndhng
